In [1]:
import numpy as np
from Autograd import WhyyTorch as wt
import matplotlib.pyplot as plt

In [2]:
"""
What:Creating a Training dataset for the bigram neural network
Why: NN take numbers as input so to predict th next most probable character we need to convert the characters into numbers, and make pairs of characters to train the model on.
"""
words = open('bigram.txt').read().splitlines()
stoi = {'.': 0, **{chr(ord('a') + i): i + 1 for i in range(26)}} 
itos = {i: c for c, i in stoi.items()}
count = 0
print(f"Our Dictionary :{stoi}")
xs,ys = [],[]
for w in words:
        count += 1
print(count)
print(f"Total Words :{count}")

Our Dictionary :{'.': 0, 'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10, 'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15, 'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26}
32033
Total Words :32033


In [16]:
#Building the dataset
block_size = 3
X,Y = [],[]
for w in words[:5]:
    context = [0] * block_size
    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        context = context[1:] + [ix]
        print(''.join(itos[i] for i in context), '->', itos[ix])
        
X = wt(X)
Y = wt(Y)

..e -> e
.em -> m
emm -> m
mma -> a
ma. -> .
..o -> o
.ol -> l
oli -> i
liv -> v
ivi -> i
via -> a
ia. -> .
..a -> a
.av -> v
ava -> a
va. -> .
..i -> i
.is -> s
isa -> a
sab -> b
abe -> e
bel -> l
ell -> l
lla -> a
la. -> .
..s -> s
.so -> o
sop -> p
oph -> h
phi -> i
hia -> a
ia. -> .


In [18]:
X.shape,X.data.dtype, Y.shape,Y.data.dtype,X,Y

((32, 3),
 dtype('float32'),
 (32,),
 dtype('float32'),
 Label: None Value: [[ 0.  0.  0.]
  [ 0.  0.  5.]
  [ 0.  5. 13.]
  [ 5. 13. 13.]
  [13. 13.  1.]
  [ 0.  0.  0.]
  [ 0.  0. 15.]
  [ 0. 15. 12.]
  [15. 12.  9.]
  [12.  9. 22.]
  [ 9. 22.  9.]
  [22.  9.  1.]
  [ 0.  0.  0.]
  [ 0.  0.  1.]
  [ 0.  1. 22.]
  [ 1. 22.  1.]
  [ 0.  0.  0.]
  [ 0.  0.  9.]
  [ 0.  9. 19.]
  [ 9. 19.  1.]
  [19.  1.  2.]
  [ 1.  2.  5.]
  [ 2.  5. 12.]
  [ 5. 12. 12.]
  [12. 12.  1.]
  [ 0.  0.  0.]
  [ 0.  0. 19.]
  [ 0. 19. 15.]
  [19. 15. 16.]
  [15. 16.  8.]
  [16.  8.  9.]
  [ 8.  9.  1.]] Grad: [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0

In [28]:
np.random.seed(42)
C = wt(np.random.randn(27, 2))

In [45]:
X.data.shape

(32, 3)

In [68]:
emb = C.data[X.data.astype(int)]
emb_wt = wt(emb.reshape(-1, 6))
emb_wt.shape

(32, 6)

In [69]:
W1 = wt(np.random.randn(6, 100))
b1 = wt(np.random.randn(100))

In [71]:
h = wt.tanh(emb_wt @ W1 + b1)
h.shape

(32, 100)

In [73]:
W2 = wt(np.random.randn(100, 27))
b2 = wt(np.random.randn(27))

In [75]:
logits = h @ W2 + b2
logits.shape

(32, 27)

In [76]:
count = logits.exp()
probs = count / count.sum(axis=1, keepdims=True)

In [88]:
loss = -np.log(probs.data[np.arange(Y.data.shape[0]), Y.data.astype(int)]).mean()
print(loss)

18.328281
