In [ ]:
import sys
from pathlib import Path

sys.path.insert(0, str(Path("..") / "00-foundation"))

import numpy as np 
from Autograd import WhyyTorch as wt

In [98]:
#Input image and kernel
img = np.array([
    [4, 5, 3, 10, 5, 12],
    [-4, -5, 6, 2, 1, 2],
    [7, 9, 9, 3, 2 ,16],
    [-1, -2, 3, 4, 5, -9],
    [1, 2, 3, -14, 5, -7],
    [1, 2, 3, 4, 5, 6]])

kernel =np.array([
    [1, 1], 
    [1, -1]])

bais = np.random.rand()

In [69]:
bais

0.6753360732506238

In [ ]:
# Feature map output
output = np.zeros((
    len(img) - len(kernel) + 1,
    len(img[0]) - len(kernel[0]) + 1
))

# Convolution operation
for i in range(len(img)-len(kernel)+1):
    for j in range(len(img[0])-len(kernel[0])+1):
        patch = img[i:i+len(kernel), j:j+len(kernel[0])]
        result = patch * kernel
        output[i][j] = np.sum(result) + bais

output = np.maximum(0, output)

In [82]:
output

array([[10.67533607,  0.        , 17.67533607, 16.67533607],
       [ 0.        ,  1.67533607, 14.67533607,  4.67533607],
       [17.67533607, 13.67533607, 11.67533607,  4.67533607],
       [ 0.        ,  0.67533607, 24.67533607,  0.        ]])

In [96]:
# Max pooling operation
stride = 2
pool_size = 2
pooled_output = np.zeros((
    (output.shape[0] - pool_size) // stride + 1,
    (output.shape[1] - pool_size) // stride + 1
))

for i in range(0, output.shape[0] - pool_size + 1, stride):
    for j in range(0, output.shape[1] - pool_size + 1, stride):
        patch = output[i:i+pool_size, j:j+pool_size]
        pooled_output[i//stride][j//stride] = np.max(patch)
    


In [97]:
pooled_output

array([[21.63908519]])

In [99]:
# Multiple Filters 
num_filters = 5

kernels = np.random.randn(num_filters, 3, 3)
biases = np.random.randn(num_filters)
all_feature_maps = []

In [100]:

for i in range(num_filters):
    kernel = kernels[i]
    bias = biases[i]
    
    output = np.zeros((
        len(img) - len(kernel) + 1,
        len(img[0]) - len(kernel[0]) + 1
    ))
    
    for j in range(len(img)-len(kernel)+1):
        for k in range(len(img[0])-len(kernel[0])+1):
            patch = img[j:j+len(kernel), k:k+len(kernel[0])]
            result = patch * kernel
            output[j][k] = np.sum(result) + bias
    
    output = np.maximum(0, output)
    
    pooled_output = np.zeros((
        (output.shape[0] - pool_size) // stride + 1,
        (output.shape[1] - pool_size) // stride + 1
    ))
    
    for j in range(0, output.shape[0] - pool_size + 1, stride):
        for k in range(0, output.shape[1] - pool_size + 1, stride):
            patch = output[j:j+pool_size, k:k+pool_size]
            pooled_output[j//stride][k//stride] = np.max(patch)
    
    print(f"Filter {i+1} Pooled Output:\n{pooled_output}\n")
    all_feature_maps.append(pooled_output)

all_feature_maps = np.stack(all_feature_maps, axis=-1)

Filter 1 Pooled Output:
[[14.09842163 37.16289177]
 [21.22948222 30.62863392]]

Filter 2 Pooled Output:
[[ 0.          0.        ]
 [ 0.         24.37402529]]

Filter 3 Pooled Output:
[[17.26629837  0.        ]
 [17.53149995 24.4549154 ]]

Filter 4 Pooled Output:
[[33.37336554 16.34132608]
 [ 9.31588027 19.91472878]]

Filter 5 Pooled Output:
[[25.89838545 23.59481515]
 [15.25935993 28.4815243 ]]



In [105]:
print(all_feature_maps.shape)
print(all_feature_maps)

(2, 2, 5)
[[[14.09842163  0.         17.26629837 33.37336554 25.89838545]
  [37.16289177  0.          0.         16.34132608 23.59481515]]

 [[21.22948222  0.         17.53149995  9.31588027 15.25935993]
  [30.62863392 24.37402529 24.4549154  19.91472878 28.4815243 ]]]


In [106]:
all_feature_maps[:,:,0]

array([[14.09842163, 37.16289177],
       [21.22948222, 30.62863392]])

In [ ]:
# A RGB image with 3 channels (Red, Green, Blue)
img = np.random.randn(6, 6, 3)

# Multiple Filters 
num_filters = 5

kernels = np.random.randn(num_filters, 3, 3, 3)  # 3 channels for RGB
biases = np.random.randn(num_filters)
all_feature_maps = []

for i in range(num_filters):
    kernel = kernels[i]
    bias = biases[i]
    
    output = np.zeros((
        img.shape[0] - kernel.shape[0] + 1,
        img.shape[1] - kernel.shape[1] + 1
    ))
    
    for j in range(img.shape[0]-kernel.shape[0]+1):
        for k in range(img.shape[1]-kernel.shape[1]+1):
            patch = img[j:j+kernel.shape[0], k:k+kernel.shape[1]]
            result = patch * kernel
            output[j][k] = np.sum(result) + bias
    
    output = np.maximum(0, output)
    
    pooled_output = np.zeros((
        (output.shape[0] - pool_size) // stride + 1,
        (output.shape[1] - pool_size) // stride + 1
    ))
    
    for j in range(0, output.shape[0] - pool_size + 1, stride):
        for k in range(0, output.shape[1] - pool_size + 1, stride):
            patch = output[j:j+pool_size, k:k+pool_size]
            pooled_output[j//stride][k//stride] = np.max(patch)
    
    print(f"Filter {i+1} Pooled Output:\n{pooled_output}\n")
    all_feature_maps.append(pooled_output)

all_feature_maps = np.stack(all_feature_maps, axis=-1)